name: Code Quality Checks

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Black
      uses: lgeiger/black-action@master
      with:
        args: ""